# Generated by Django 4.2.30 on 2026-07-11 10:27

from django.db import migrations, models
import django.db.models.deletion
import papers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('exam_type', models.CharField(choices=[('Internal', 'Internal'), ('Mid Semester', 'Mid Semester'), ('End Semester', 'End Semester'), ('Supplementary', 'Supplementary')], default='End Semester', max_length=50)),
                ('pdf_file', models.FileField(upload_to=papers.models.paper_upload_path)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('ocr_processed', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='departments.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='departments.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='subjects.subject')),
            ],
            options={
                'ordering': ['-academic_year'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField()),
                ('processed_date', models.DateTimeField(auto_now_add=True)),
                ('question_paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_text', to='papers.questionpaper')),
            ],
        ),
    ]
