# Generated by Django 6.1 on 2026-09-14 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_extractedtext_extraction_metadata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionpaper',
            name='ocr_processed',
        ),
        migrations.DeleteModel(
            name='ExtractedText',
        ),
    ]
