# Generated by Django 6.1 on 2026-09-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_remove_questionpaper_ocr_processed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='exam_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Supplementary', 'Supplementary')], default='Regular', max_length=50),
        ),
    ]
