# Generated by Django 6.1 on 2026-09-14 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('papers', '0003_remove_questionpaper_ocr_processed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(help_text='Page number where this question starts (1-indexed)')),
                ('question_number', models.CharField(help_text="e.g., '1', '13', 'Part A'", max_length=20)),
                ('part', models.CharField(blank=True, help_text="e.g., 'a', 'b', 'i'", max_length=10, null=True)),
                ('question_text', models.TextField()),
                ('raw_text_block', models.TextField(help_text='The exact raw text chunk containing this question')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_questions', to='papers.questionpaper')),
            ],
            options={
                'ordering': ['page_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('extraction_method', models.CharField(choices=[('NATIVE', 'Native Text (PyMuPDF)'), ('OCR', 'OCR (PaddleOCR)'), ('MIXED', 'Mixed (Native + OCR)'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('pages_processed', models.IntegerField(default=0)),
                ('total_pages', models.IntegerField(default=0)),
                ('questions_extracted', models.IntegerField(default=0)),
                ('character_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_status', to='papers.questionpaper')),
            ],
        ),
    ]
