# Generated by Django 4.2.30 on 2026-09-14 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
        ('ai_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectAnalysisCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results_json', models.JSONField(blank=True, help_text='Stored semantic analysis results', null=True)),
                ('last_computed', models.DateTimeField(auto_now=True)),
                ('is_stale', models.BooleanField(default=False, help_text='True if new questions were added since last analysis')),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='subjects.subject')),
            ],
        ),
    ]
