# Generated by Django 4.2.30 on 2026-09-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0002_subjectanalysiscache'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedquestion',
            name='marks',
            field=models.CharField(blank=True, help_text="Extracted marks (e.g., '10', '5x2=10')", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='extractionstatus',
            name='extraction_method',
            field=models.CharField(choices=[('NATIVE', 'Native Text (PyMuPDF)'), ('OCR', 'OCR (Tesseract / PaddleOCR fallback)'), ('MIXED', 'Mixed (Native + OCR)'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20),
        ),
    ]
