# Generated by Django 4.2.30 on 2026-09-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0003_extractedquestion_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedquestion',
            name='section',
            field=models.CharField(blank=True, help_text="Section of the paper (e.g., 'A', 'B')", max_length=50, null=True),
        ),
    ]
